service:
  session_ttl: 12h
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "master"
  sslmode: "disable"
  max_open_conns: 5
redis:
  addr: "localhost:6379"
